### ISSUE TITLE
How do I navigate the deserialized data?

### ISSUE THREAD

**Issue by Krutonium** [shravan2x/Gameloop.Vdf#1]
Trying to get each item in a key just gives me an array of each letter that was there... I am completely lost. And I don't seem to be able to navigate to sub-keys either >.>

**Comment by shravan2x** [comment]
Not sure what you mean, can you give me an idea of what you're trying to deserialize?

For example, I'd use something like this to navigate the TF2 Schema:

```
string vdf = File.ReadAllText("tf2schema.vdf");
dynamic prop = VdfConvert.Deserialize(vdf);
Console.WriteLine(prop.Value["qualities"]["vintage"]);
Console.WriteLine(prop.Value["items"]["918"]["name"]);
```

Schema : http://api.steampowered.com/IEconItems_440/GetSchema/v0001/?key=KEY&format=vdf

I think your confusion may lie with the fact that `Values` of `VProperties` are always just `VTokens`. These may really be more `VProperty`s or `VObject`s. So treating the root key as `dynamic` really simplifies things.

P.S. I'm trying to make it more Json.NET style, where you could do something like `prop.qualities.vintage`, but I just can't get it to work for some reason.

**Comment by Krutonium** [comment]
http://media.steampowered.com/controller_config/firmware/firmware.vdf This and Hmmm... I'll try that in the morning.

**Comment by shravan2x** [comment]
This worked for me:

```
dynamic prop = VdfConvert.Deserialize(firmware);
foreach (dynamic firmwareType in prop.Value["4354"].Children())
    Console.WriteLine(firmwareType.Value["firmwarebinary"]);
```

and printed:

```
/firmware/vcf_wired_controller_d0g_55393371.bin
/firmware/vcf_wired_controller_d0g_555bf9c5.bin
/firmware/vcf_wired_controller_d0g_5567949d.bin
/firmware/vcf_wired_controller_d0g_556e46b0.bin
/firmware/vcf_wired_controller_d0g_557248e3.bin
...
```

**Comment by Krutonium** [comment]
Sorry, I meant to reply - thanks, this worked :+1:
