### ISSUE TITLE
How to update/edit array values

### ISSUE THREAD

**Issue by agc93** [shravan2x/Gameloop.Vdf#13]
I'm attempting to add a key/value pair to an existing array and can't seem to get the types to match up.

Using a VDF like the following:

```text
"GameInfo"
{
	"game"		"sample"
	"FileSystem"
	{
		"SteamAppId"	"111"
		"SearchPaths"
		{
			"Game"	"|gameinfo_path|."
			"Game"	"search"
			"Game"	"path"
		}
	}
}
```

I would have expected code like the below to work (this sample won't even compile):

```csharp
var parsed = VdfConvert.Deserialize(File.ReadAllText("./gameinfo.txt"));
var values = parsed.Value["FileSystem"]["SearchPaths"].Cast<VProperty>();
parsed.Value["FileSystem"]["SearchPaths"] = values.Append(new VProperty("Game", new VValue("test")));
```

Is there something basic I'm missing here? I can provide a slightly more detailed repro if needed.

**Comment by shravan2x** [comment]
The VDF format doesn't have arrays. From your example, it seems like you're trying to add another property to the `"SearchPaths"` object. You can do that like this:

```cs
VProperty parsed = VdfConvert.Deserialize(File.ReadAllText("./gameinfo.txt"));
VObject obj = parsed.Value["FileSystem"]["SearchPaths"] as VObject;
obj.Add(new VProperty("Game", new VValue("test")));
Console.WriteLine(parsed);
```

The result is:
```
"GameInfo"
{
        "game" "sample"
        "FileSystem"
        {
                "SteamAppId" "111"
                "SearchPaths"
                {
                        "Game" "|gameinfo_path|."
                        "Game" "search"
                        "Game" "path"
                        "Game" "test"
                }
        }
}
```
<br/>

**EXTRA**:
Usually, you can also just do this to set a new property in the object:
```cs
VObject obj = parsed.Value["FileSystem"]["SearchPaths"] as VObject;
obj["Game"] = new VValue("test");
```

However, if the `obj` contains duplicate `"Game"` keys, it would only update the first one. So we are forced to use `obj.Add` here like I did above.

**Comment by agc93** [comment]
That works perfectly! Thanks so much for the quick help, I just knew it would be something simple.

Still wrapping my head around the VDF format so thanks for the detail!
