### ISSUE TITLE
Sucks up backslashes

### ISSUE THREAD

**Issue by Bluscream** [shravan2x/Gameloop.Vdf#16]
```

//
// Use this file to mount additional paths to the filesystem
// DO NOT add a slash to the end of the filename
//

"mountcfg"
{
	// "cstrike"			"C:\steamcmd\steamapps\common\Counter-Strike Source Dedicated Server\cstrike"
	// "tf"					"C:\mytf2server\tf"
	"bms"					"S:\Steam\steamapps\common\Black Mesa\bms"
	"downfall"				"S:\Steam\steamapps\common\Half-Life 2 DownFall\downfall"
	"EntropyZero"			"S:\Steam\steamapps\common\Entropy Zero\Entropy Zero\EntropyZero"
	// "hl2update"			"S:\Steam\steamapps\common\Half-Life 2 Update\hl2"
	"portal_stories"		"S:\Steam\steamapps\common\Portal Stories Mel\portal_stories"
	"TWTM"					"S:\Steam\steamapps\common\Thinking with Time Machine\TWTM"
	"csco"					"S:\Steam\steamapps\sourcemods\csco"
	"thecitizenreturns"		"S:\Steam\steamapps\sourcemods\thecitizenreturns"
	"watchingpaintdry"		"S:\Steam\steamapps\sourcemods\watchingpaintdry"
	// "HL2MMod"				"S:\Steam\steamapps\sourcemods\HL2MMod"
	// "HL2MMod_HL2"			"S:\Steam\steamapps\sourcemods\HL2MMod_HL2"
	// "HL2MMod_HL2U"			"S:\Steam\steamapps\sourcemods\HL2MMod_HL2U"
	// "HL2MMod_Cinematic_HL2"	"S:\Steam\steamapps\sourcemods\HL2MMod_Cinematic_HL2"
	// "HL2MMod_EP1"			"S:\Steam\steamapps\sourcemods\HL2MMod_EP1"
	// "HL2MMod_Cinematic_EP1"	"S:\Steam\steamapps\sourcemods\HL2MMod_Cinematic_EP1"
	// "HL2MMod_EP2"			"S:\Steam\steamapps\sourcemods\HL2MMod_EP2"
	// "HL2MMod_Cinematic_EP2"	"S:\Steam\steamapps\sourcemods\HL2MMod_Cinematic_EP2"
	// "HL2MMod_LC"				"S:\Steam\steamapps\sourcemods\HL2MMod_LC"
	// "HL2MMod_METASTASIS"		"S:\Steam\steamapps\sourcemods\HL2MMod_METASTASIS"
}
```
this file from gmod gets sadly corrupted by Gameloop.vdf:

![](https://cdn.discordapp.com/attachments/554907029785935872/696491072397901824/image.png)

**Comment by Bluscream** [comment]
Also it would be nice if it could read commented lines so i can "enable/disable" them

**Comment by shravan2x** [comment]
> this file from gmod gets sadly corrupted by Gameloop.vdf:

By default, Gameloop.Vdf supports escape sequences. So the parser tries to identify escape sequences for the backslashes in your `VValue`s and fails to do so. You can change this behavior using the `UsesEscapeSequences` flag in `VdfSerializerSettings`. A quick shortcut is to use `VdfSerializerSettings.Default` (eg. `VdfConvert.Deserialize(..., VdfSerializerSettings.Default)`).

> Also it would be nice if it could read commented lines so i can "enable/disable" them

Could you create a separate issue for this? I'm happy to treat it as a feature request. It seems that Json.NET [supports this too](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_CommentHandling.htm).

**Comment by Bluscream** [comment]
Works fine, thank you :heart:
