### ISSUE TITLE
Allow reading / writing comments

### ISSUE THREAD

**Issue by Bluscream** [shravan2x/Gameloop.Vdf#18]
It would be nice if the parser would try to parse commented lines and fallback to just storing them as strings when parsing fails (a regular comment)

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bluscream** [comment]
I did something similar for another app once (it was regex tho):
https://github.com/Bluscream/MWR-Config-Editor/blob/master/CFGParser/Classes/CFGFile.cs#L28

**Comment by Bluscream** [comment]
Any news on this @shravan2x? my app is [depending on it](https://github.com/Bluscream/GMod-Mount-Manager/blob/master/UI/Main.cs#L222) :c

**Comment by shravan2x** [comment]
> Any news on this @shravan2x? my app is depending on it :c

I didn't realize it was blocking, I'll work on it this weekend. But can't you just save without the comments?

> I did something similar for another app once (it was regex tho):

I can't use Regex for performance reasons.

**Comment by Bluscream** [comment]
> I didn't realize it was blocking, I'll work on it this weekend. But can't you just save without the comments?

In my case the comments are used as "Disabled Entries" and they would be lost and had to be recreated

**Comment by shravan2x** [comment]
@Bluscream Which of the following types of comments do you plan to use?

```js
// Comment type A (at the start of the file)
"root"
{
    // Comment type B (as a child to an object)
    key1 "value1"
    "key2" // Comment type C (to the right of a property name)
    {
        "key3" "value3" // Comment type D (to the right of a property value)
    }
}
// Comment type E (at the end of the file)
```

Would it suffice if deserializing then re-serializing this file resulted in this?

```js
"root"
{
        // Comment type B (as a child to an object)
        "key1" "value1"
        "key2"
        {
                "key3" "value3"
                // Comment type D (to the right of a property value)
        }
}
```

**Comment by Bluscream** [comment]
Only B is important to me when serializing but i think when deserializing it might be good to be able to get the others aswell

**Comment by shravan2x** [comment]
I've built support for comments locally, I plan to commit them to the repo in the next few days and then release `0.6.0`. So far, this is the progress:
- A - unsupported (i.e. ignored)
- B - full support
- C - unsupported (i.e. ignored)
- D - supported, but is moved to a new line during serialization
- E - unsupported (i.e. ignored)

There are challenges associated with supporting the others, especially A and E (until #23 is resolved, there's no place to store these comments). I'll leave this issue open and revisit it after #23. But hopefully, support for B and D will unblock you.

**Comment by shravan2x** [comment]
Resolved with 0855a05203bf380e807e3aa3112544addae8451b, I'll push 0.6.0 soon.

Note that this update includes a breaking change - `myvobject.Children()` now returns `IEnumerable<VToken>` instead of `IEnumerable<VProperty>`. If you want the old behavior, use `myvobject.Properties()` instead.

**Comment by shravan2x** [comment]
Fyi to create a comment from code you do `VValue.CreateComment("some comment string")`.

**Comment by Bluscream** [comment]
When is this pushed to nuget so i can use it in production?

**Comment by shravan2x** [comment]
Sorry, I'm polishing some other NRT issues on VObject because otherwise they'd become breaking changes in 0.7.0 (which I plan to add support for conditionals in). I'll push it tomorrow.

**Comment by shravan2x** [comment]
@Bluscream `0.6.0` is out.

**Comment by Bluscream** [comment]
I might pick the project back up soon, so thanks <3
