### ISSUE TITLE
Add VDF-JSON converter

### ISSUE THREAD

**Issue by shravan2x** [shravan2x/Gameloop.Vdf#2]
This should work both ways. A separate package should probably be used.

**Comment by Erlite** [comment]
Is this still going to be added?

**Comment by shravan2x** [comment]
Yeah I'll try to do it this week.

**Comment by Erlite** [comment]
I'm currently trying to do it myself so I'll see if I can help.

**Comment by shravan2x** [comment]
Someone seems to have made some headway on this over at https://github.com/gbryer/Gameloop.Vdf/commit/66728c6b1b07f51aab620f2321db6b0c423439a0. I don't want to add a dependency to the core package so it should probably go in `Gameloop.Vdf.ToJson` or something.

**Comment by shravan2x** [comment]
I have created a new repo for this at [Gameloop.Vdf.JsonConverter](https://github.com/shravan2x/Gameloop.Vdf.JsonConverter). Please track progress there.

**Comment by shravan2x** [comment]
The new package is available on NuGet at https://www.nuget.org/packages/Gameloop.Vdf.JsonConverter.
