### ISSUE TITLE
Deserialize error when the string contains "//"

### ISSUE THREAD

**Issue by a6874453** [shravan2x/Gameloop.Vdf#27]
Hello, I got deserialize error when the VDF string contains "//" in Gameloop.Vdf 0.6.0
Sample VDF:

```
"Test"
{
	"Key1"	"//"
}
```

**Comment by shravan2x** [comment]
Thanks for reporting this, it seems to have crept in with the comment support in `0.6.0`. I've added a test so it doesn't break again. I'll push `0.6.1` by tonight.

**Comment by shravan2x** [comment]
FYI `0.6.1` has been pushed to NuGet and should be available soon.
