### ISSUE TITLE
Steam reverts changes made by Gameloop

### ISSUE THREAD

**Issue by yuukiw** [shravan2x/Gameloop.Vdf#3]
i want to write an launch option to the vdf.
the strange thing about it is that if i paste the same line manually it doesnt revert it.
the code can be found here:
https://github.com/yuukiw/SDVMMR/blob/master/SDVMMR/Functions/WriteToVDF.cs

**Comment by shravan2x** [comment]
Have you tried this with the latest [0.4](https://github.com/shravan2x/Gameloop.Vdf/releases/tag/Vdf.NET_0.4.0)?

**Comment by yuukiw** [comment]
yes

**Comment by shravan2x** [comment]
Alright, I found some time to study this problem earlier today. The main cause appears to be that Steam's own VDF files follow largely different formats for line termination and assignment (The file you modify, **localconfig.vdf**, uses type 2) :

1. **controller_generic_gamepad_joystick.vdf** (Assign='\t' or ' ', LineTerminator='\r\n')
![image](https://user-images.githubusercontent.com/4096676/29739933-451bf9e0-8a10-11e7-8b7a-3d29a76e23e2.png)


2. **remotecache.vdf** (Assign='\t', LineTerminator='\n')
![image](https://user-images.githubusercontent.com/4096676/29739929-2562361e-8a10-11e7-9002-32ce20df0255.png)

3. **empty.vdf** (Assign=' ', LineTerminator='\r\n')
![image](https://user-images.githubusercontent.com/4096676/29739948-da4ce826-8a10-11e7-800b-1a0ae822ed06.png)

I will likely allow these to be configured in the settings and setup reasonable defaults for them.

**Comment by shravan2x** [comment]
_I had posted a previous message here suggesting that this might be caused by differing whitespace characters. However, that does not appear to be the case. Please disregard that._

I attempted to generate VDF using the **localconfig.vdf** file and replaced the original. Steam does indeed rewrite the file in order to update timestamps and such, but it did not _revert_ anything in my case.

Could you email me a copy of the **localconfig.vdf** that Vdf.NET generates?

**Comment by yuukiw** [comment]
its based on the string steam itself adds to the file

**Comment by yuukiw** [comment]
here is the file you asked for  (
https://github.com/shravan2x/Gameloop.Vdf/issues/3#issuecomment-325108916 )

2017-08-26 11:45 GMT+02:00 Shravan Rajinikanth <notifications@github.com>:

**Comment by shravan2x** [comment]
I think your link is incorrect?

**Comment by yuukiw** [comment]
huh. didnt know it would automaticly post here when i send a email. the file is in the email i send.

**Comment by shravan2x** [comment]
The email you sent was probably to GitHub itself. You can email me at mail@shrav.me.

**Comment by yuukiw** [comment]
did send a email. Interestingly while trying it out it seemed to have worked one time but each time after that it will still revert the change

**Comment by shravan2x** [comment]
Could you build and try again with the latest code?

Make the following changes:
[Line 78](https://github.com/yuukiw/SDVMMR/blob/master/SDVMMR/Functions/WriteToVDF.cs#L78): `string path = Path.Combine(MainWindow.SDVMMSettings.GameFolder, "StardewModdingAPI.exe");`
[Line 79](https://github.com/yuukiw/SDVMMR/blob/master/SDVMMR/Functions/WriteToVDF.cs#L79): `VValue launchOptions = new VValue($" \"{path}\" %command%");`
[Line 82](https://github.com/yuukiw/SDVMMR/blob/master/SDVMMR/Functions/WriteToVDF.cs#L82): `File.WriteAllText(files[i], VdfConvert.Serialize(raw), Encoding.UTF8);`

If you're unable to, you can try `0.4.1` which I'll be pushing in a while.

**EDIT**: Added encoding on Line 82.
**EDIT 2**: You _may_ not need the encoding on Line 82. It appears to be a UTF-8 BOM issue somewhere. Possibly with WinMerge, but I'm not sure. WinMerge (which I use to diff the files locally) complains if I don't use the encoding, but comparing the files bytes-to-bytes suggests that leaving out the encoding is the correct one.

**UPDATE**: I've just pushed [0.4.1](https://www.nuget.org/packages/Gameloop.Vdf/0.4.1).

**Comment by yuukiw** [comment]
0.4.1 works
