### ISSUE TITLE
Something wrong with conditional

### ISSUE THREAD

**Issue by DokAndMax** [shravan2x/Gameloop.Vdf#36]
I have vdf file and when I try to deserialize a file (example below) I get an exception 'Incomplete VDF data. I've found out that the exception appears when the file contains an odd number of conditionals, but with an even number of conditionals the program works fine.

> "lang"
> {
> 	"Language" "English"
> 	"Tokens"
> 	{
> 	// ---------------------------------------------------------------------------------------------
> 	// GAMEUI_ENGLISH.txt
> 		"GameUI_MainMenuMovieScene"	"Main Menu Background Scenery" [$X360]
> 		"GameUI_MainMenuMovieScene_Vanity"	"Change Background Scenery"
> 		"GameUI_MainMenuMovieScene_Tooltip"	"This setting allows you to customize the main menu background scenery which sets the mood for visual experience of your entire game."
> 		"GameUI_DisplayMode"		"Color Mode"
> 	}
> }
>

**Comment by shravan2x** [comment]
@DokAndMax The library doesn't support conditionals at the moment. We have a tracking task for this at #12 . Could you share where you found this particular VDF file?

**Comment by shravan2x** [comment]
I'm guessing your snippet is from the csgo_english.txt file. I'm working on adding support for conditionals now. Follow #12 for updates.

**Comment by DokAndMax** [comment]
> I'm guessing your snippet is from the csgo_english.txt file.

You're right.

> @DokAndMax The library doesn't support conditionals at the moment. 

My issue isn't about conditional support, sorry if I was unclear. I mean, avoiding conditionals seems doesn't work properly (at the time of issue creation), therefore I describe unexpected behaviour in the issue description.

I think there is might problem with this piece of code:
https://github.com/shravan2x/Gameloop.Vdf/blob/af630d6acbd2e3a9ccbe8d260726cca50e11eea2/Gameloop.Vdf/VdfTextReader.cs#L182-L185

**Comment by shravan2x** [comment]
@DokAndMax Unfortunately, until just now in eb8b8b8bc5a4b0d4d20dd0fd85b77679d4b9a9b1, we didn't support avoiding conditionals either. I've seen some users just strip them from files using a regex before parsing.

If possible, please try the latest commit on the master branch. It has full support for conditionals, including automatically evaluating conditionals during deserialization (if you enable it).

I intend to push conditionals support as 0.7.0 i n the next few days.

**Comment by chte** [comment]
Any eta on when 0.7.0 is coming out?
