### ISSUE TITLE
Could be an issue, just posting my problem.

### ISSUE THREAD

**Issue by Twigzie** [shravan2x/Gameloop.Vdf#37]
I have this config file that I just assume is VDF inside one of my game installations called "app.config". Im writing a program but want to make sure the selected folder is in fact a steam game folder.

Here is the file:
```
{  
	"xal":
	{  
		"title_id":1144039928,
		"service_config_id":"77290100-225e-4768-9373-98164430a9f8",
		"client_id":"000000004825FC1F"
	},
	"steam":
	{
		"app_id":976730
	}
}
```

I did what the README said to do:
```
dynamic data = VdfConvert.Deserialize(File.ReadAllText("app.config"));
```

My issue is that I only have access to the property "xal":
![image](https://user-images.githubusercontent.com/1693796/227808536-8f392381-939c-42d4-987b-934410f3b082.png)

If the file I'm using isn't a valid VDF, please excuse my assumptions and close this issue, thanks!

**Comment by shravan2x** [comment]
The file you posted appears to be a standard JSON file. You can use STJ to deserialize it like `JsonSerializer.Deserialize(...)`.
